kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: proxy-service
spec:
  selector:
    app: proxy
  ports:
  - protocol: TCP
    port: 30000
    nodePort: 30000
    targetPort: health-check
    name: health-check
  - protocol: TCP
    port: 30002
    nodePort: 30002
    targetPort: epp
    name: epp
  - protocol: TCP
    port: 30001
    nodePort: 30001
    targetPort: whois
    name: whois
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: default
  name: proxy-autoscale
  labels:
    app: proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proxy-deployment
  maxReplicas: 50
  minReplicas: 10
