apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: proxy-deployment
  labels:
    app: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: us-central1-docker.pkg.dev/ud-registry-crash/nomulus/proxy
        ports:
        - containerPort: 30000
          name: health-check
        - containerPort: 30002
          name: epp
        readinessProbe:
          tcpSocket:
            port: health-check
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: health-check
          initialDelaySeconds: 15
          periodSeconds: 20
        imagePullPolicy: Always
        args: ["--env", "crash", "--log"]
        env:
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONTAINER_NAME
          value: proxy
