# Builds the image to run SQL after the initial database migration has been run.
# Build and upload the roles-initializer image.
steps:
- id: Copy-Sql-Files-To-Working-Dir
  name: '$_GCR_HOSTNAME/${PROJECT_ID}/nomulus/builder:latest'
  entrypoint: /bin/bash
  args:
  - -c
  - |
    set -e
    # Copy the SQL files to the working directory.
    cp db/src/main/resources/sql/user/initialize_roles.sql release/roles-initializer
    cp db/src/main/resources/sql/user/set_flyway_privileges.sql release/roles-initializer
- id: Build-Image-And-Push
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/bash
  args:
  - -c
  - |
    set -e
    docker build -t $_GCR_HOSTNAME/${PROJECT_ID}/nomulus/roles-initializer:${COMMIT_SHA} --build-arg PROJECT_ID=${PROJECT_ID} --build-arg GCR_HOSTNAME=$_GCR_HOSTNAME .
    docker tag $_GCR_HOSTNAME/${PROJECT_ID}/nomulus/roles-initializer:${COMMIT_SHA} \
      $_GCR_HOSTNAME/${PROJECT_ID}/nomulus/roles-initializer:latest
    docker push $_GCR_HOSTNAME/${PROJECT_ID}/nomulus/roles-initializer:${COMMIT_SHA}
    docker push $_GCR_HOSTNAME/${PROJECT_ID}/nomulus/roles-initializer:latest
  dir: 'release/roles-initializer/'
timeout: 3600s
options:
  pool: 
    name: 'projects/${PROJECT_ID}/locations/us-central1/workerPools/cloudbuild-pool-test-2'
substitutions:
  _GCR_HOSTNAME: us-central1-docker.pkg.dev
  _GCS_STORAGE_BUCKET_FOR_CLOUDBUILD: "ud-registry-crash-nomulus-deploy-cloudbuild-logs"
logsBucket: "$_GCS_STORAGE_BUCKET_FOR_CLOUDBUILD"
images: ['$_GCR_HOSTNAME/${PROJECT_ID}/nomulus/roles-initializer:${COMMIT_SHA}']
