# This will create a docker image named gcr.io/[PROJECT_ID]/proxy:[TAG] locally.
# The PROJECT_ID is the current project name that gcloud uses.
#
# To manually trigger a build on GCB, run:
# gcloud builds submit --config cloudbuild-proxy.yaml --substitutions TAG_NAME=[TAG] ..
#
# To trigger a build automatically, follow the instructions below and add a trigger:
# https://cloud.google.com/cloud-build/docs/running-builds/automate-builds
steps:
# Check the out internal repo. 
- id: Clone-Internal-Repo
  name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/bash
  secretEnv:
    - GITHUB_OAUTH_TOKEN
  args:
  - -c
  - |
    set -e
    git config --global credential.helper store
    echo "https://oauth2:$$GITHUB_OAUTH_TOKEN@github.com" > ~/.git-credentials
    git clone https://github.com/unstoppabledomains/nomulus-secrets.git nomulus-internal
- id: Merge-Internal-Repo
  name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/bash
  args:
  - -c
  - |
    set -e
    shopt -s dotglob
    rm -rf .git && rm -rf nomulus-internal/.git
    cp -rf nomulus-internal/* .
    rm -rf nomulus-internal
# Build the proxy docker image.
- id: Deploy-Nomulus-Proxy
  name: '$_GCR_HOSTNAME/${PROJECT_ID}/nomulus/builder:latest'
  entrypoint: /bin/bash
  args:
  - -c
  - |
    ./deploy-proxy-for-env.sh ${_ENV}
  dir: 'proxy'
timeout: 3600s
options:
  pool: 
    name: 'projects/${PROJECT_ID}/locations/us-central1/workerPools/cloudbuild-pool-test-2'

substitutions:
  _ENV: crash
  _GCR_HOSTNAME: us-central1-docker.pkg.dev
  _GCS_STORAGE_BUCKET_FOR_CLOUDBUILD: "ud-registry-crash-nomulus-deploy-cloudbuild-logs"
  _COMMIT_SHA: ${COMMIT_SHA}
  _GITHUB_TOKEN_SECRET_NAME: unstoppabledomains-org-github-oauthtoken-9b9658

logsBucket: "$_GCS_STORAGE_BUCKET_FOR_CLOUDBUILD"

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/${_GITHUB_TOKEN_SECRET_NAME}/versions/latest
    env: GITHUB_OAUTH_TOKEN
