# To manually trigger a build on GCB, run:
# gcloud builds submit --config ud-cloudbuild-run-tests.yaml --substitutions \
#   _INTERNAL_REPO_URL=[URL] ..
#
# To trigger a build automatically, follow the instructions below and add a trigger:
# https://cloud.google.com/cloud-build/docs/running-builds/automate-builds
#
# This pipeline runs tests against the Nomulus code.
steps:
# Check the out internal repo. 
- id: Clone-Internal-Repo
  name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/bash
  secretEnv:
    - GITHUB_OAUTH_TOKEN
  args:
  - -c
  - |
    set -e
    git config --global credential.helper store
    echo "https://oauth2:$$GITHUB_OAUTH_TOKEN@github.com" > ~/.git-credentials
    git clone https://github.com/unstoppabledomains/nomulus-secrets.git nomulus-internal
# Merge the repos. 
- id: Merge-Internal-Repo
  name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/bash
  args:
  - -c
  - |
    set -e
    shopt -s dotglob
    rm -rf .git && rm -rf nomulus-internal/.git
    cp -rf nomulus-internal/* .
    rm -rf nomulus-internal
# Build the builder image and pull the base images, them upload them to GCR.
- id: Build-Builder-Base-Image-And-Push
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/bash
  args:
  - -c
  - |
    set -e
    docker build -t $_GCR_HOSTNAME/${PROJECT_ID}/nomulus/builder-test:${COMMIT_SHA} .
    docker tag $_GCR_HOSTNAME/${PROJECT_ID}/nomulus/builder-test:${COMMIT_SHA} $_GCR_HOSTNAME/${PROJECT_ID}/nomulus/builder-test:latest
    docker push $_GCR_HOSTNAME/${PROJECT_ID}/nomulus/builder-test:${COMMIT_SHA}
    docker push $_GCR_HOSTNAME/${PROJECT_ID}/nomulus/builder-test:latest
  dir: 'release/builder/'
# Run tests
- id: Run-Tests
  name: '$_GCR_HOSTNAME/${PROJECT_ID}/nomulus/builder-test:latest'
  # Set home for Gradle caches.
  env: [ 'GRADLE_USER_HOME=/workspace/cloudbuild-caches' ]
  args: ['./gradlew',
         'test',
         '-PskipDockerIncompatibleTests=true',
         '-PmavenUrl=https://repo.maven.apache.org/maven2',
         '-PpluginsUrl=https://plugins.gradle.org/m2'
  ]
timeout: 3600s
options:
  pool: 
    name: 'projects/${PROJECT_ID}/locations/us-central1/workerPools/cloudbuild-default'
substitutions:
  _GCR_HOSTNAME: us-central1-docker.pkg.dev
  _GCS_STORAGE_BUCKET_FOR_CLOUDBUILD: "ud-registry-crash-nomulus-deploy-cloudbuild-logs"
  _GITHUB_TOKEN_SECRET_NAME: unstoppabledomains-org-github-oauthtoken-9b9658
logsBucket: "$_GCS_STORAGE_BUCKET_FOR_CLOUDBUILD"

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/${_GITHUB_TOKEN_SECRET_NAME}/versions/latest
    env: GITHUB_OAUTH_TOKEN
