# Add environment-specific configuration here.
gcpProject:
  # projectId: nomulus-pre-alpha
  # projectIdNumber: 241446389074
  projectId: nomulus-pre-alpha2
  projectIdNumber: 264643765037
  locationId: us-central1
  isLocal: false
  defaultServiceUrl: https://default-dot-nomulus-pre-alpha2.appspot.com
  backendServiceUrl: https://backend-dot-nomulus-pre-alpha2.appspot.com
  bsaServiceUrl: https://bsa-dot-nomulus-pre-alpha2.appspot.com
  toolsServiceUrl: https://tools-dot-nomulus-pre-alpha2.appspot.com
  pubapiServiceUrl: https://pubapi-dot-nomulus-pre-alpha2.appspot.com
  baseDomain: nomulus-pre-alpha2.appspot.com

registryTool:
  # OAuth client ID used by the tool.
  # OAuth client secret used by the tool.

  clientId: PLACEHOLDER
  clientSecret: PLACEHOLDER

oAuth:
  availableOauthScopes:
  - https://www.googleapis.com/auth/cloud-platform
  - https://www.googleapis.com/auth/appengine.apis
  - https://www.googleapis.com/auth/userinfo.email
  - https://www.googleapis.com/auth/appengine.admin
  requiredOauthScopes:
  - https://www.googleapis.com/auth/userinfo.email

cloudSql:
  jdbcUrl: jdbc:postgresql://localhost:15432/
  instanceConnectionName: nomulus-pre-alpha2:us-central1:nomulus-pre-alpha

auth:
  # OAuth 2.0 client ID that will be used as the audience in OIDC ID tokens sent
  # from clients (e.g., proxy, nomulus tool, cloud tasks) for authentication. The
  # same ID is the only one accepted by the regular OIDC or IAP authentication
  # mechanisms. In most cases, we should use the client ID created for IAP here,
  # as it allows requests bearing a token with this audience to be accepted by
  # both IAP or regular OIDC. The clientId value in proxy config file should be
  # the same as this one.
  oauthClientId: PLACEHOLDER